apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-58d817b6f2c34e729a8fe7c42131986f-depl
  labels:
    app: coll-58d817b6f2c34e729a8fe7c42131986f
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-58d817b6f2c34e729a8fe7c42131986f
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-58d817b6f2c34e729a8fe7c42131986f
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-58d817b6f2c34e729a8fe7c42131986f
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-58d817b6f2c34e729a8fe7c42131986f
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping